- snippets/custom-text-selection.md
Discrepancy between example HTML and CSS classnames. I chose the one used in the demo/html.
> Corrected classname for text selection demo.

- snippets/pretty-text-underline.md
The caveat described is visible in Firefox, at least.
> Add caveat to Pretty Text Underline

- snippets/truncate-text.md
Ellipsis isn't the same as three dots: https://en.wikipedia.org/wiki/Ellipsis
`…` `!==` `...`
> Fix ellipsis character

- snippets/overflow-scroll-gradient.md
This disables pointer events on the pseudo element so that it won't block clicks to the content element.
> Disable pointer events on pseudo element

- index.html
the back to top button and menu button each lack appropriate accessible names.
The primary page navigation is presently contained within an `aside` rather than a `nav` element.
This commit adds accessible names to the previously mentioned buttons, so they will be appropriately conveyed to screen readers.  It also changes the navigation from an `aside` to `nav` and provides the navigation with an `aria-label=“table of contents”` as all the links are in page links to the different sections of this document.
> accessibility: update buttons and nav semantics

- index.html
Let's optimize this site for search. Getting lots of traction here, wanting to help you have it discovered organically, more, too!
The current meta description is pulling from main element, starting with Clearfix section/snippet, since no explicit meta description is provided.
No real search value within the current SERP, here: 
This PR/commit adds a meta description to this project site. Let me know if looking for a different description, I simply wrote based off what's currently on-page and with optimizations for specific, searched terms in-mind ;-)
> [FIX] Addition of meta description

- package.json
On windows we can't run build task. It's because of this:
`[error] No matching files. Patterns tried: ./js/index.js './src/**/*.js' './src/**/*.scss' !**/node_modules/** !./node_modules/**`
Well, I know, windows!?!... :)
It's because of not escapping quotes I belive.
If we need the quotes, I can escape the double them.
Win 10
Node ~8
Of course, it runs on a vm. I tested in vagrant/ubuntu.
Also, I have two small questions  :)
- In the same [L10(with the prettier task)](https://github.com/atomiks/30-seconds-of-css/pull/51/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R10), what do we need `./js/index.js` for?
- What about some help instructions on how to npm run tasks on the readme file?
> fix(build): prettier win paths

- snippets/pretty-text-underline.md
#22 
@xori can you check if using `px` instead fixes it?
> [FIX] Use px values for pretty text underline

- snippets/constant-width-to-height-ratio.md
Using `float` modifies the computed `display` value of the element. Therefore, the `display` property in the snippet is unnecessary.
Source: https://developer.mozilla.org/en-US/docs/Web/CSS/float
> [FIX] Remove the display property from 'Constant width and height ration' snippet

- snippets/last-item-with-all-available-height.md
1. typo for file name
2. replace `flex:1` with `flex-grow:1` in snippet
> [FIX] typo for file name and replace `flex: 1` with `flex-grow: 1`

- snippets/counter.md
[Counter snippet](https://github.com/30-seconds/30-seconds-of-css/blob/master/snippets/counter.md) contains different HTML code in snippet and demo, this PR fixes it.
Also small typo fixes.
> [FIX] Make HTML in Counter snippet the same as demo 

- snippets/popout-menu.md
**Description**
This change keeps the popout-menu open when the focus is inside the body of the reference element. e.g. when a button/link is focused inside the popout element.
This is _especially_ important to the people relying on a keyboard for navigating through websites, thus the **a11y** tag.
**Changes:**
- Added `focus-within` pseudo class to show the popout when the focus is inside the element
- Added relevant points to "Explanation" section
> [Enhancement] [a11y] Improvements to popout-menu snippet

- snippets/bouncing-loader.md
Delete `from{}` from `@keyframes` rule cause it is not necessary in this case of 2 states, the animation takes the default values of the element `opacity: 1` and `transform: translateY(0)`.
Although the x-axis or y-axis is used in the 2d plane, transform: translate3d(0,0,0) is used because it improves the performance of the animation.
> [FIX] Changes in the @keyframes rule

- README.md
We're closing our Gitter and Slack channels - very few used it, and we can be 100% reliable on issues and PR's
> Delete Gitter link

- snippets/zebra-striped-list.md
I just saw the `Zebra striped list` snipped in the `30 Seconds of Knowledge` Chrome Extension and couldn't clearly see a contrast, because the background-color is too light.
On bad screens it's probably not visible at all, we should make it a bit darker.
> [FIX] use darker color to have a clear contrast

- snippets/remove-inline-block-container-white-space.md
- snippets/tile-layout-using-inline-block.md
Align items horizontally without float, flexbox, and grid. 100% browser support and support old browsers
> [feature] inline block snippet 

- snippets/transform-detransform.md
This snippet is aimed for setting a transform on a container element and de-transforming its child contents.
I added a few stylized rules to the `.parent` element to make the preview look a little prettier. I can remove these if requested.
> [FEATURE] Add snippet for transform/detransform

- snippets/hamburger-button.md
The hamburger button page was titled "Hamburguer Button", so I corrected it to "Hamburger Button" (no `uer` at the end of hamburger, just `er`)
> [FIX] Fixing a typo in the title of the hamburger button

- snippets/masonry-layout.md
I'd like to add this CSS-based Masonry layout. It's great for showcasing an online portfolio and is especially useful to photographers and digital artists. The main benefit is that no JS-based library is needed, which makes it possible for the browser to directly place the "bricks", without having to wait for some render script.
I'm using it myself to create 'cards' for my blog overview and for my online portfolio.
> [FEATURE] Add CSS-based (vertical) Masonry-layout

- snippets/tile-layout-using-inline-block.md
as per the title
Reference of note: https://css-tricks.com/fighting-the-space-between-inline-block-elements/#set-the-font-size-to-zero
> update: tile-layout-using-inline-block with a side note

- snippets/vertical-scroll-snap.md
Fixed a spelling mistake from 'display: gird' to 'display: grid'
> Fixed spelling of display value

- snippets/horizontal-scroll-snap.md
The container 'horizontal-snap' will overflow on mobile phone. Cause by the fixed width.
> The container 'horizontal-snap' will overflow on mobile phone.
