30-seconds/30-seconds-of-css

LICENSE
Adds CC0 1.0 Universal License to the repo (same one as 30-seconds-of-code).
=> [LICENSE] Creative Commons Zero v1.0 Universal

snippets/disable-selection.md
Add a snippet disable-selection
=> [FEATURE] Create disable-selection.

snippets/hover-underline-animation.md
=> [FEATURE] Hover underline animation

snippets/box-sizing-reset.md
=> [FEATURE] Adding box-sizing-reset snippet.

index.html, snippets/custom-scrollbar.md, snippets/scrollbars-styling.md
=> [FEATURE] Add scrollbars-styling

index.html, snippets/hairline-border.md, snippets/hover-underline-animation.md, snippets/overflow-scroll-gradient.md, snippets/shape-separator.md
Hi there,
Just a quick fix to get rid of these nasty typos ;-).
Jérémy.
=> [FIX] 7 typos psuedo instead of pseudo

index.html, src/js/components/Menu.js
@scottaohara this should fix it
=> [FIX #28]: Accessibility concerns

snippets/reset-all-styles.md
=> [FEATURE] Add reset-all-styles snippet

snippets/sibling-fade.md
Reupload sibling-fade.md as requested
=> [FEATURE] Create sibling-fade.md

snippets/dynamic-shadow.md
Creates a shadow similar to `box-shadow` but based on the colors of the element itself.
=> [FEATURE] Dynamic shadow

snippets/grid-layout.md
Separate PR for `grid-layout` snippet since there were some issues in #58. I am merging this right away as @Chalarangelo already reviewed it.
=> add grid-layout snippet

index.html, package-lock.json, snippets/counter.md
New branch created for the property Counter
=> [FEATURE] Add Counter property

snippets/counter.md
=> [FIX] Clean counter snippet

snippets/height-transition.md
Transitions an element's height from `0` to `auto` when its height is unknown.
=> [FEATURE] Height transition

README.md
=> Add repository links

snippets/pretty-text-underline.md
add u tag as another alternative
=> add u tag as another alternative

snippets/counter.md
=> [FIX] Grammar fix

snippets/truncate-text-multiline.md
Multiline truncate text
Resolves #133
=> [FEATURE] Add multiline truncate text

index.html, snippets/hover-shadow-box-animation.md
=> fix: spelling mistake

snippets/not-selector.md
=> [FIX] Typo change

snippets/border-with-top-triangle.md
Please forgive my poor English. 🙈
Something like this:
=> [FEATURE] Add border with top triangle snippet

snippets/drop-cap.md
Adding a CSS snippet to create drop caps 😅
=> [FEATURE]: Add Drop Cap Snippet

snippets/navigation-list-item-hover-and-focus-effect.md
Hover, focus effect for the navigation items by using `before` pseudo-element, and utilizing `transform: scale()` property.
=> [FEATURE]navigation list item hover and focus effect

CONTRIBUTING.md
=> beginner typo

snippets/lobotomizedOwlSelector.md
=> [FEATURE] Create lobotomizedOwlSelector.md snippet

snippets/pulse-loader.md
Would like to add a pulse loader made using CSS Animation property
=> Added snippet for pulse-loader

snippets/hamburger-button.md
This is simple way to build hamburger button.
=> [FEATURE] Adding simple way to build hamburger button.

snippets/offscreen.md
While it may have originally been innocuous, it is now leading to a scam click site
Resolves #164
=> [FIX] Remove a link that has become dangerous

snippets/border-with-top-triangle.md, snippets/clearfix.md
Fix some snippets that would break the new website. Just reordering and cleaning some content.
=> Fix breaking snippets

snippets/hamburger-button.md
Updated the hamburger menu to be easier to understand and prevent the jitter on hover
=> [FIX] Updated hamburger button snippet to be clearer

snippets/masonry-layout.md
Corrected a typo in snippets/masonry-layout.md file
=> [FIX] Corrected a typo

snippets/border-with-top-triangle.md
=> (fix) add double colon notation

snippets/image-hover-menu.md, snippets/image-hover-rotate.md, snippets/image-overlay-hover.md
=> Fix broken images

snippets/rotating-card.md
**Is this a new component ?**
Yes
**About the component**
This component is a two sided card which flips/rotates on hover and switches sides. It uses the rotateY transform property to create the rotating effect.
**Code Pen**
You can find a working codepen example in the following link
https://codepen.io/taimoor0217-the-styleful/pen/vYGorJe
=> add rotating-card

snippets/input-with-prefix.md
**Is this a new component?**
Yes
**About the component**
This component is an input box with a non-editable prefix.
**Code Pen**
You can find a working codepen example in the following [link](https://codepen.io/TGLIDE/pen/BazjBNX).
=> add input-with-prefix.md

snippets/floating-list-titles.md
=> Reuse "height", the second "height" may be "width"

snippets/button-hover-fill-animation.md
Is this a new component ?
Yes
About the component
This is a button that has a fill animation on hover/action.
Code Pen
You can find a working codepen example in the following link
https://codepen.io/hwilson2563/pen/jOrEWLM
** is it possible to add this as a valid [Hacktoberfest Contribution](https://hacktoberfest.digitalocean.com/hacktoberfest-update) by assigning an official label 😃 ?
=> add button-hover-fill-animation

snippets/zoomin-zoomout-animation.md
A CSS animation snippet which applies a zoom in and zoom out animation to a box element.
=> Add zoom in zoom out animation
